---
- name: remove artifact file
  file:
    path: "{{ tmp_repo }}"
    state: absent
- name: Install PIP
  apt: name=python-pip state=present
- name: Install lxml
  pip: name=lxml
- name: Nexus Artifact deploy
  maven_artifact:
    group_id: pl.codeleak.demos.sbt
    artifact_id: spring-boot-thymeleaf
    extension: war
    version: 2.0.0
    repository_url: "{{ deploy_url }}"
    username: admin
    password: admin
    dest: "{{ tmp_repo }}"
    mode: '0755'
- name: Deploy in tomcat
  copy:
    src: "{{ tmp_repo }}"
    dest: "{{ tomcat_latest }}/webapps/{{ deploy_file_name }}"
    mode: '0755'
    remote_src: yes
  notify:
    - reload the daemon, enable and start the tomcat service
