- name: Install Java
  apt:
      name: openjdk-11-jdk
      state: latest
  
- name: Install Tomcat
  get_url:
      url: (( tomcat_url }}
      dest: /usr/local

- name: Unarchive Tomcat Package
  unarchive:
      src: /usr/local/{{ tomcat_package }}
      dest: /usr/local
      remote_src: yes
